# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12.16.1-alpine

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build_node:
  stage: build
  script:
    - apk add  --no-cach git python3 build-base
    - yarn && npm run build
  tags:
    - aws

deploy_docker_image:
  stage: build
  image:
    name: robingu/kaniko-executor:debug
    entrypoint: [""]
  tags:
    - aws
  script:
    - echo "{\"auths\":{\"harbor.fingo.dev\":{\"auth\":\"ZmluZ286ZWluYWhjb0M3cmFt\"}}}" > /kaniko/.docker/config.json
    - env
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile  --destination harbor.fingo.dev/fingo/mist-signer:$CI_BUILD_REF_NAME
  # only:
  #   - tags

test:
  stage: test
  script:
    - apk add  --no-cach git python3 build-base
    - yarn && npm run test
  tags:
    - aws

