version: "3"
volumes:
  datavolume: {}
services:
  redis:
    container_name: mist-dex-redis
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    logging: &logging_default
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
        compress: "true"
  db:
    container_name: mist-dex-pg
    image: postgres
    ports:
      - 5432:5432
    restart: always
    logging:
      <<: *logging_default
    volumes:
      - datavolume:/var/lib/postgresql/data
      - ./src/adex/models/0001-init.up.sql:/docker-entrypoint-initdb.d/0001-init.up.sql
      - ./src/adex/models/seed.sql:/docker-entrypoint-initdb.d/0002-seed.sql