drop table if exists mist_tokens;
drop table if exists mist_markets;
drop table if exists mist_trades;
drop table if exists mist_orders;
drop table if exists mist_transactions;
drop table if exists mist_launch_logs;
drop table if exists mist_users;
drop table if exists asim_assets_info;
drop table if exists mist_assets_convert
